services:
  mPass-server:
    image: ghcr.io/mpassw/mpass-server
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - Server__EncryptionKey=${SERVER_ENCRYPTION_KEY}
      - Server__UseSwagger=${SERVER_USE_SWAGGER}
      - Auth__SecurityKey=${AUTH_SECURITY_KEY}
      - Auth__Issuer=${AUTH_ISSUER}
      - Smtp__Host=${SMTP_HOST}
      - Smtp__Port=${SMTP_PORT}
      - Smtp__Username=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASSWORD}
      - Smtp__Sender=${SMTP_SENDER}
      - Smtp__EnableSsl=${SMTP_ENABLE_SSL}
      - Postgres__ConnectionString=Host=postgres;Port=5432;Database=mPass;Username=mpass;Password=${POSTGRES_PASSWORD}
      - Redis__Host=redis
      - Redis__Port=6379
      - Redis__Password=${REDIS_PASSWORD}
    networks:
      - mPass-network

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mpass
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mPass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mPass-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - mPass-network

networks:
  mPass-network:

volumes:
  postgres-data: